version: '3'
services:
  nginx:
    image: finbloxui-www
    container_name: finbloxui-www
    restart: unless-stopped
    tty: true
    build:
      context: ../
      dockerfile: ./infra/configs/www/Dockerfile
      args:
        env: dev
    volumes:
      - ./:/usr/src
      # this allows npm to successfully install all modules
      - /usr/src/node_modules
    ports:
      - 7080:80
    networks:
      - finbloxui-network
#Docker Networks
networks:
  finbloxui-network:
    name: api_finbloxui-network
    driver: bridge