# storage: ./storage
storage: /verdaccio/storage/data
plugins: /verdaccio/plugins
auth:
  finbloxui-auth:
    foo: bar
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  '@*/*':
    proxy: npmjs
    # access: $all,
    access: $authenticated
    publish: $authenticated
  '**':
    proxy: npmjs
    access: $authenticated
    publish: $authenticated
  '@finbloxui/*':
    access: $authenticated
    publish: admin
    unpublish: admin
log:
  - { type: stdout, format: pretty, level: http }