version: '3'
services:
  api:
    image: finbloxui-api
    container_name: finbloxui-api
    build:
      context: ../
      dockerfile: ./infra/api/server/Dockerfile
      args:
        node_cmd: nodemon
        node_args: --ext js,yml,yaml
    # only use volumes for dev
    volumes:
      - ./:/usr/src/api
      # this allows npm to successfully install all modules
      - /usr/src/api/node_modules
    networks:
      - finbloxui-network
    ports:
      - 3001:3000
  db:
    container_name: finbloxui-db
    image: mysql:5.7.35 # latest seems to hang on digital ocean
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: finbloxui
      MYSQL_USER: finbloxui
      MYSQL_PASSWORD: 'pass22pass'
      MYSQL_ROOT_PASSWORD: root # for dev only
    ports:
      - 7033:3306
    volumes:
      - finbloxui-data:/var/lib/mysql/
      - ../../infra/api/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - finbloxui-network
#Docker Networks
networks:
  finbloxui-network:
    driver: bridge
#Volumes
volumes:
  finbloxui-data:
    driver: local