name: Build and publish manually

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true
env:
  REGISTRY: "registry.digitalocean.com/sports-camp-360"
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v3
      - name: Build webserver image 
        run: docker build -t finbloxui-www --progress=plain --no-cache --build-arg env=prod -f ./infra/configs/www/Dockerfile .
      - name: Install doctl 
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DO Container Registry 
        run: doctl registry login --expiry-seconds 600
      - name: Tag finbloxui-www image with last commit
        run: docker tag finbloxui-www ${{ env.REGISTRY }}/finbloxui-www:${{ github.sha }}
      - name: Tag finbloxui-www image as latest
        run: docker tag finbloxui-www ${{ env.REGISTRY }}/finbloxui-www:latest
      - name: Push finbloxui-www image last commit to DO Container Registry 
        run: docker push ${{ env.REGISTRY }}/finbloxui-www:${{ github.sha }}
      - name: Push finbloxui-www image latest to DO Container Registry 
        run: docker push ${{ env.REGISTRY }}/finbloxui-www:latest
  deploy:
    needs: build_and_push
    uses: eseyfried/finbloxui/.github/workflows/deploy.yml@main
    secrets: inherit