# finbloxui-containers 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
name: Build and publish api manually

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true
env:
  REGISTRY: "ghcr.io"
  IMAGE_NAME: "finbloxui-api"
jobs:
  build_and_push_api:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      #   with:
      #     images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          file: ./infra/api/server/Dockerfile
          build-args: env=prod
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:latest, ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
  # build_and_push_api:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout the repo 
  #       uses: actions/checkout@v3
  #     - name: Build api image 
  #       run: docker build -t finbloxui-api --progress=plain --no-cache --build-arg env=prod -f ./infra/api/server/Dockerfile .
  #     - name: Install doctl 
  #       uses: digitalocean/action-doctl@v2
  #       with:
  #         token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
  #     - name: Log in to DO Container Registry 
  #       run: doctl registry login --expiry-seconds 600
  #     - name: Tag finbloxui-api image with last commit
  #       run: docker tag finbloxui-api ${{ env.REGISTRY }}/finbloxui-api:${{ github.sha }}
  #     - name: Tag finbloxui-api image as latest
  #       run: docker tag finbloxui-api ${{ env.REGISTRY }}/finbloxui-api:latest
  #     - name: Push finbloxui-api image last commit to DO Container Registry 
  #       run: docker push ${{ env.REGISTRY }}/finbloxui-api:${{ github.sha }}
  #     - name: Push finbloxui-api image latest to DO Container Registry 
  #       run: docker push ${{ env.REGISTRY }}/finbloxui-api:latest
  # deploy-api:
  #   needs: build_and_push_api
  #   uses: eseyfried/finbloxui/.github/workflows/deploy-api.yml@main
  #   secrets: inherit