# finbloxui-containers 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
name: Build and publish registry manually

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true
env:
  REGISTRY: "ghcr.io"
  IMAGE_NAME: "finbloxui-registry"
jobs:
  build_and_push_registry:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          file: ./infra/verdaccio/Dockerfile
          build-args: env=prod
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:latest, ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
  deploy-registry:
    needs: build_and_push_registry
    uses: eseyfried/finbloxui/.github/workflows/deploy-registry.yml@main
    secrets: inherit