name: Deploy Registry
on:
  workflow_call:
  workflow_dispatch:
    inputs:
      version:
        description: "Image Version"
        required: true
env:
  REGISTRY: "ghcr.io"
  REGISTRY_IMAGE_NAME: "finbloxui-registry"
  REGISTRY_CONTAINER_NAME: "registry"
jobs:
  deploy-registry:
    runs-on: ubuntu-latest
    steps:
      - name: "Deploy to Digital Ocean droplet via ssh Action"
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          debug: true
          envs: REGISTRY_IMAGE_NAME,REGISTRY_CONTAINER_NAME,${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }},GITHUB_SHA
          script: |
            # login to registry
            docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ${{ env.REGISTRY }}
            # stop running containers
            docker stop ${{ env.REGISTRY_CONTAINER_NAME }}
            # remove running containers
            docker rm ${{ env.REGISTRY_CONTAINER_NAME }}
            # Pull latest images
            docker pull ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.REGISTRY_IMAGE_NAME }}:${{ github.event.inputs.version }} 
  run-registry-container:
    needs: deploy-registry
    uses: eseyfried/finbloxui/.github/workflows/run-registry-container.yml@main
    secrets: inherit  