name: Test Action
on:
  workflow_dispatch:
    # outputs:
    #   version:
    #     description: NPM package version
    #     value: ${{ jobs.test-set-version.outputs.version }}
jobs:
#   job1:
#     runs-on: ubuntu-latest
#     outputs:
#       output1: ${{ steps.step1.outputs.test }}
#       output2: ${{ steps.step2.outputs.test }}
#     steps:
#       - id: step1
#         run: echo "test=hello" >> $GITHUB_OUTPUT
#       - id: step2
#         run: echo "test=world" >> $GITHUB_OUTPUT
#   job2:
#     runs-on: ubuntu-latest
#     needs: job1
#     steps:
#       - env:
#           OUTPUT1: ${{needs.job1.outputs.output1}}
#           OUTPUT2: ${{needs.job1.outputs.output2}}
#         run: echo "$OUTPUT1 $OUTPUT2"
  test-set-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    steps:
      - id: set-version
        run: echo "version=1.0.7" >> $GITHUB_OUTPUT
  update-version:
    runs-on: ubuntu-latest
    needs: test-set-version
    steps:
    - name: debugging
      run: echo "${{ needs.test-set-version.outputs.version }}"
    # uses: eseyfried/finbloxui/.github/workflows/update-npm-manifest.yml@main
    # with:
    #   version: ${{ needs.test-set-version.outputs.version }}
      # version: "1.0.7"