name: Update NPM Manifest
on:
  workflow_call:
    inputs:
      version:
        description: 'NPM version'
  workflow_dispatch:
jobs:
  update-npm-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: POST NPM Version
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://api.finbloxui.com/version'
          method: 'POST'
          # username: ${{ secrets.AWX_USER }}
          # password: ${{ secrets.AWX_PASSWORD }}
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{ "version": "${{ inputs.version}}"}'